SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE _user_badges;
TRUNCATE TABLE _heroes;
TRUNCATE TABLE def_roles;
TRUNCATE TABLE _accounts;
TRUNCATE TABLE _contest_prizes;
TRUNCATE TABLE def_contest_places;
TRUNCATE TABLE def_games;
TRUNCATE TABLE old_score_total;
TRUNCATE TABLE def_contest_types;
TRUNCATE TABLE _user_logins;
TRUNCATE TABLE _backgrounds;
TRUNCATE TABLE _boxes;
TRUNCATE TABLE _notifications;
TRUNCATE TABLE score_contests;
TRUNCATE TABLE _caretakers;
TRUNCATE TABLE _users;
TRUNCATE TABLE _hero_files;
TRUNCATE TABLE score_games;
TRUNCATE TABLE def_hero_file_types;
TRUNCATE TABLE _contests;
TRUNCATE TABLE score_games_archive;
TRUNCATE TABLE old_user_contests;
TRUNCATE TABLE def_mail_templates;
TRUNCATE TABLE def_pointed_activities;
TRUNCATE TABLE _sponsors;
TRUNCATE TABLE def_ranks;
TRUNCATE TABLE def_badges;
TRUNCATE TABLE score_pointed_activities;
TRUNCATE TABLE _static_sites;
TRUNCATE TABLE old_contests;
TRUNCATE TABLE _slides;
TRUNCATE TABLE _user_movies_likes;
TRUNCATE TABLE _user_movies;
TRUNCATE TABLE _notification_statuses;
TRUNCATE TABLE _video_ads;

SET FOREIGN_KEY_CHECKS=1;
