TEXT_GAMEOVER    = "Koniec gry!";
TEXT_CONGRATS    = "Gratulacje";
TEXT_PLAY        = "Graj";
TEXT_SCORE       = "Wynik";
TEXT_LEVEL       = "Poziom";
TEXT_FINAL_SCORE = "Wynik końcowy";
TEXT_SELECT_LEVEL = "Wybierz poziom";
TEXT_DELETE_SAVINGS = "Przepadnie cały Twój postęp w grze? Na pewno chcesz grać od nowa?";
TEXT_NO = "Nie";
TEXT_YES = "Tak";
var TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.";
TEXT_CREDITS_DEVELOPED = "Nagrody funduje";

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Gratulacje!";
TEXT_SHARE_MSG1 = "Udało Ci się zdobyć <strong>";
TEXT_SHARE_MSG2 = " punktów</strong>!<br><br>Całkiem nieźle!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better";